groups:
  - name: shelly_monitor_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          service: shelly-monitor
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"
          
      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s (threshold: 2s)"
          
      # Device offline
      - alert: DeviceOffline
        expr: active_devices{status="offline"} > 0
        for: 10m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "Device(s) offline"
          description: "{{ $value }} device(s) have been offline for more than 10 minutes"
          
      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 500
        for: 5m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "High memory usage"
          description: "Process memory usage is {{ $value }}MB (threshold: 500MB)"
          
      # Database connection pool exhaustion
      - alert: DatabaseConnectionPoolExhausted
        expr: database_connection_pool_size{state="waiting"} > 10
        for: 2m
        labels:
          severity: critical
          service: shelly-monitor
        annotations:
          summary: "Database connection pool exhausted"
          description: "{{ $value }} connections waiting in pool"
          
      # Rate limiting triggered frequently
      - alert: HighRateLimitHits
        expr: rate(rate_limit_hits_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "High rate limit hits"
          description: "Rate limiting is being triggered {{ $value }} times per second"
          
      # Authentication failures
      - alert: HighAuthenticationFailures
        expr: rate(auth_attempts_total{status="failure"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value | humanizePercentage }}"
          
      # API latency
      - alert: HighAPILatency
        expr: api_latency_seconds{quantile="0.99"} > 5
        for: 5m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "High API latency"
          description: "99th percentile API latency is {{ $value }}s for {{ $labels.endpoint }}"
          
      # Cache hit rate
      - alert: LowCacheHitRate
        expr: |
          (
            rate(cache_hits_total[5m]) / 
            (rate(cache_hits_total[5m]) + rate(cache_misses_total[5m]))
          ) < 0.8
        for: 10m
        labels:
          severity: info
          service: shelly-monitor
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (threshold: 80%)"
          
      # Power consumption anomaly
      - alert: HighPowerConsumption
        expr: power_consumption_watts > 1000
        for: 15m
        labels:
          severity: warning
          service: shelly-monitor
        annotations:
          summary: "High power consumption detected"
          description: "Device {{ $labels.device_id }} channel {{ $labels.channel }} consuming {{ $value }}W"